/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemarodoviarioclient;

import funcionarioTela.CadastroFuncionario;
import javax.swing.SwingUtilities;

/**
 *
 * @author Eduardo
 */
public class MenuPricipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPricipal
     */
    public MenuPricipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butCadastroFuncionario = new javax.swing.JButton();
        butCadastroOnibus = new javax.swing.JButton();
        butListaFuncionario = new javax.swing.JButton();
        butListaOnibus = new javax.swing.JButton();
        butCadastroRota = new javax.swing.JButton();
        butListaRota = new javax.swing.JButton();
        butCadstroLinha = new javax.swing.JButton();
        butListaLinha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butCadastroFuncionario.setText("Cadastro de Funcionário");
        butCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCadastroFuncionarioActionPerformed(evt);
            }
        });

        butCadastroOnibus.setText("Cadastro de Ônibus");

        butListaFuncionario.setText("Listar Funcionários");

        butListaOnibus.setText("Listar Ônibus");

        butCadastroRota.setText("Cadastro de Rotas");

        butListaRota.setText("Listar Rotas");

        butCadstroLinha.setText("Cadastro de Linhas");

        butListaLinha.setText("Listar Linhas");

        jLabel1.setText("Cadastros");

        jLabel2.setText("Listas");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(butCadastroOnibus)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 107, Short.MAX_VALUE)
                .add(butListaOnibus)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(butCadastroFuncionario)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(butListaFuncionario))
            .add(layout.createSequentialGroup()
                .add(butCadstroLinha)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(butListaLinha))
            .add(layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .add(70, 70, 70))
            .add(layout.createSequentialGroup()
                .add(butCadastroRota)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(butListaRota))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butCadstroLinha)
                    .add(butListaLinha))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butCadastroFuncionario)
                    .add(butListaFuncionario))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butCadastroOnibus)
                    .add(butListaOnibus))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(butCadastroRota)
                    .add(butListaRota))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCadastroFuncionarioActionPerformed
//        cadastroFuncionarioerrado cf = new cadastroFuncionarioerrado();
//        cf.setVisible(true);
        CadastroFuncionario cf = new CadastroFuncionario();
        this.setContentPane(cf);
        SwingUtilities.updateComponentTreeUI(this);
        cf.setVisible(true);
    }//GEN-LAST:event_butCadastroFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuPricipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCadastroFuncionario;
    private javax.swing.JButton butCadastroOnibus;
    private javax.swing.JButton butCadastroRota;
    private javax.swing.JButton butCadstroLinha;
    private javax.swing.JButton butListaFuncionario;
    private javax.swing.JButton butListaLinha;
    private javax.swing.JButton butListaOnibus;
    private javax.swing.JButton butListaRota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
